### ISSUE TITLE
make neo4j can't started

### ISSUE THREAD

**Issue by Donghuanyu** [neo4j-contrib/neo4j-elasticsearch#20] opened 2016-05-18 08:18 UTC
hello,I did what you said:
1.Clone this repository and run `mvn install -DskipTests`
2.Copy the `jar` files in `target/dependency` to your Neo4j instance's
  `plugins` folder
3.Also copy `target/neo4j-elasticsearch-2.3-SNAPSHOT.jar` to the
  `plugins` folder
4.Modify `conf/neo4j.conf` accordingly like this:
   elasticsearch.host_name=http://localhost:9200
   elasticsearch.index_spec=actor:Actor(name), director:Director(name),                  movie:Movie(title),person:Person(name), user:User(name)
5.Restart Neo4j

and I'm sure the elasticsearch service run in the localhost:9200
but,when I restart Neo4j,it can't start,there are error on starting:

**ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@12108f0d' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@12108f0d' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@12108f0d' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:217)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:81)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:60)
        at org.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@12108f0d' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:189)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.enterprise.EnterpriseFacadeFactory, /home/wonders/develop/noe4j/neo4j-enterprise-3.0.1/data/databases/graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:144)
        at org.neo4j.kernel.impl.enterprise.EnterpriseFacadeFactory.newFacade(EnterpriseFacadeFactory.java:42)
        at org.neo4j.graphdb.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:57)
        at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$1(EnterpriseNeoServer.java:85)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@761166bb' failed to initialize. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:416)
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
        ... 10 more
Caused by: java.lang.AbstractMethodError
        at org.neo4j.kernel.extension.KernelExtensions.init(KernelExtensions.java:69)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
        ... 13 more**

I can't find where is the wrong.I hope you can help me.
Thanks.

**Comment by az-ericso** [comment] 2016-05-18 21:45
+1 

I am having the same issue.

**Comment by Donghuanyu** [comment] 2016-05-19 03:35
@az-ericso  hi,are you have already solve this problem?if you have,can you help me?

**Comment by Donghuanyu** [comment] 2016-05-19 08:56
I solved this problem.this is the version cause this problem.I use NEO4J 3.0.1,so I change the NEO4J's version 2.0.3 to 3.0.1 in the program.and there are some change in code at ElasticSearchKernelExtensionFactory.java. like this:

```
`@Description("Settings for the Elastic Search Extension")
    public static abstract class ElasticSearchSettings {
        public static Setting<String> hostName = Settings.setting("elasticsearch.host_name", Settings.STRING, (String) null);
        public static Setting<String> indexSpec = Settings.setting("elasticsearch.index_spec", Settings.STRING, (String) null);
        public static Setting<Boolean> includeIDField = Settings.setting("elasticsearch.include_id_field", Settings.BOOLEAN, "true");
        public static Setting<Boolean> includeLabelsField = Settings.setting("elasticsearch.include_labels_field", Settings.BOOLEAN,
                "true");
        // todo settings for label, property, indexName
    }
```

```
@Override
    public Lifecycle newInstance(KernelContext arg0, Dependencies dependencies) throws Throwable {

        Config config = dependencies.getConfig();

        return new ElasticSearchExtension(dependencies.getGraphDatabaseService(),
                config.get(ElasticSearchSettings.hostName), config.get(ElasticSearchSettings.indexSpec),
                config.get(ElasticSearchSettings.includeIDField), config.get(ElasticSearchSettings.includeLabelsField));
    }`
```

then build,and do what readme.adoc said.
I hope it can help you.
@az-ericso

**Comment by az-ericso** [comment] 2016-05-19 16:34
Thanks @Donghuanyu. It works for me as well.

**Comment by jexp** [comment] 2016-05-20 06:34
Good that it works for you, I tried to update to Neo4j 3.0.1 but I consistently get ES connection errors :( which I can't resolve. With ES 2.3.2

**Comment by jexp** [comment] 2016-05-20 06:37
Can you try this branch (if it works for you) and report back: https://github.com/neo4j-contrib/neo4j-elasticsearch/tree/3.0

**Comment by az-ericso** [comment] 2016-05-20 07:25
Actually, it still does not work. I have no idea why the neo4j was running. I am getting the same error using this error:
- neo4j (3.0.1) version
- both 2.3 and 3.0 branch does not work

``` sh
2016-05-20 07:24:58.924+0000 INFO  Starting...
2016-05-20 07:24:59.487+0000 ERROR ElasticSearch Integration: syntax error in index_spec
2016-05-20 07:25:00.037+0000 INFO  Bolt enabled on localhost:7687.
2016-05-20 07:25:05.784+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@29d015b4' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@29d015b4' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@29d015b4' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:217)
    at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:81)
    at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:60)
    at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@29d015b4' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:189)
    ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /var/lib/neo4j/data/databases/kancho.db
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:144)
    at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:40)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
    at org.neo4j.server.CommunityNeoServer.lambda$static$32(CommunityNeoServer.java:55)
    at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
    ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@4611a950' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
    ... 10 more
Caused by: java.lang.VerifyError: Cannot inherit from final class
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:132)
    at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:110)
    at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
    at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
    at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:85)
    at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:77)
    at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:125)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
    ... 12 more
```

**Comment by jexp** [comment] 2016-05-20 16:31
Are you running Java 8?

Von meinem iPhone gesendet

**Comment by az-ericso** [comment] 2016-05-20 16:33
``` sh
ubuntu@ip-10-0-0-72:~$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by az-ericso** [comment] 2016-05-23 21:29
can we reopen this issue?

**Comment by jexp** [comment] 2016-05-24 06:24
Did you see this error? `ElasticSearch Integration: syntax error in index_spec`

what does your index-config look like in neo4j.conf ?

**Comment by jexp** [comment] 2016-05-24 06:33
Did you clean out your plugins directory before trying again? Otherwise you might have old files in there.

I updated the instructions for building it: `mvn clean install -DskipTests`

**Comment by az-ericso** [comment] 2016-05-25 18:13
Yes, I did it. But I am still the error.

**Comment by az-ericso** [comment] 2016-05-25 22:40
omg.. it is working....

**Comment by az-ericso** [comment] 2016-05-25 22:40
I used to be a java developer but totally missed that part. Thanks 👍

**Comment by az-ericso** [comment] 2016-05-25 22:49
Seeing only this error:

``` sh
2016-05-25 22:45:25.341+0000 INFO  Starting...
2016-05-25 22:45:25.902+0000 ERROR ElasticSearch Integration: syntax error in index_spec
2016-05-25 22:45:26.424+0000 INFO  Bolt enabled on localhost:7687.
```

``` sh
elasticsearch.index_spec=product:Product(productId,productName)
```

**Comment by jexp** [comment] 2016-05-25 23:42
Where did you put it ? in conf/neo4j.conf ?

**Comment by jexp** [comment] 2016-05-25 23:49
Which ES version are you using? I have troubles with the integration test.

Does the test work for you?

see: https://travis-ci.org/neo4j-contrib/neo4j-elasticsearch

**Comment by az-ericso** [comment] 2016-05-26 00:13
I am using AWS elasticSearch service. The configuration settings is neo4j.conf.

It seems it cannot read the configuration. :(

**Comment by az-ericso** [comment] 2016-05-26 00:25
@jexp sorry that I was looking at the wrong directory. In AWS, the configuration is in /etc/neo4j/neo4j.conf instead of /var/lib/neo4j/conf/neo4j.conf.

I used the following command to find out. I hope this can help other people:

``` sh
dpkg -L neo4j
```

**Comment by az-ericso** [comment] 2016-05-26 23:47
No error in the log anymore. But nothing is stored inside elasticSearch :(

**Comment by jexp** [comment] 2016-05-27 00:24
I tested it and it worked for me, what does your index-spec look like? and what kind of data did you create in Neo4j?

**Comment by 4ossiblellc** [comment] 2016-05-27 02:12
Thanks for your quick response. I have a label named "Tech" with a field named "keyword" having words separated by "space" in a string format.

The configuration is:

``` sh
elasticsearch.index_spec=tech:Tech(keyword)
```

I put this configuration in both neo4j.conf and neo4j.properties (based on the neo4j website)

Sorry that I have another github account. I am also @az-ericso.

**Comment by jexp** [comment] 2016-05-27 07:44
Did you configure the host?

What do the nodes that you create look like?

**Comment by az-ericso** [comment] 2016-05-27 16:40
I put the following properties in the file.

``` sh
elasticsearch.host_name=https://search-<<hide>>.us-east-1.es.amazonaws.com
```

**Comment by az-ericso** [comment] 2016-05-27 16:50
Wait a min. It works now after I pulled the latest version and rebuild the .jar files.  Thanks.  Please close this ticket.

**Comment by az-ericso** [comment] 2016-05-27 16:53
thanks @jexp  👍

**Closed as completed** 2016-05-27 16:53 UTC

**Comment by MaryamMahmoodi** [comment] 2018-11-28 21:20
Hi , need your help  @jexp 
after upgrade Ubuntu 18.04.1 LTS! neo4j don't work (the version: neo4j 3.5.0)
I have this error :
2018-11-28 20:26:45.171+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@67d18ed7' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@67d18ed7' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService".

org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@67d18ed7' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService".

at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)

at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:184)

at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:122)

at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)

at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)

Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@67d18ed7' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService".

at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)

at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)

at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:177)

... 3 more

Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases

at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)

at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:134)

at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:40)

at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:78)

at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)

... 5 more

Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.GlobalKernelExtensions@2421cc4' failed to initialize. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService".

at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:434)

at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:66)

at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:102)

at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:203)

... 9 more

Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/impl/logging/LogService

at java.lang.Class.getDeclaredMethods0(Native Method)

at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)

at java.lang.Class.privateGetPublicMethods(Class.java:2902)

at java.lang.Class.getMethods(Class.java:1615)

at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:451)

at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:339)

at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:639)

at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)

at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)

at java.lang.reflect.WeakCache.get(WeakCache.java:127)

at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)

at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)

at org.neo4j.kernel.impl.util.DependenciesProxy.dependencies(DependenciesProxy.java:55)

at org.neo4j.kernel.extension.AbstractKernelExtensions.getKernelExtensionDependencies(AbstractKernelExtensions.java:111)

at org.neo4j.kernel.extension.AbstractKernelExtensions.init(AbstractKernelExtensions.java:59)

at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:413)

... 12 more

Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.impl.logging.LogService

at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)

at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

... 28 more

2018-11-28 20:26:45.172+0000 INFO Neo4j Server shutdown initiated by request

**Comment by amiteshthe** [comment] 2019-01-20 13:41
Same problem me and my colleagues are facing for more than 5 days.. When you''ll reply guys ?
Please help ASAP.

> Hi , need your help @jexp
> after upgrade Ubuntu 18.04.1 LTS! neo4j don't work (the version: neo4j 3.5.0)
> I have this error :
> 2018-11-28 20:26:45.171+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@67d18ed7' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@67d18ed7' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService".
> 
> org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@67d18ed7' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService".
> 
> at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
> 
> at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:184)
> 
> at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:122)
> 
> at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
> 
> at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
> 
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@67d18ed7' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService".
> 
> at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
> 
> at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
> 
> at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:177)
> 
> ... 3 more
> 
> Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases
> 
> at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
> 
> at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:134)
> 
> at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:40)
> 
> at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:78)
> 
> at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
> 
> ... 5 more
> 
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.GlobalKernelExtensions@2421cc4' failed to initialize. Please see the attached cause exception "org.neo4j.kernel.impl.logging.LogService".
> 
> at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:434)
> 
> at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:66)
> 
> at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:102)
> 
> at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:203)
> 
> ... 9 more
> 
> Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/impl/logging/LogService
> 
> at java.lang.Class.getDeclaredMethods0(Native Method)
> 
> at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> 
> at java.lang.Class.privateGetPublicMethods(Class.java:2902)
> 
> at java.lang.Class.getMethods(Class.java:1615)
> 
> at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:451)
> 
> at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:339)
> 
> at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:639)
> 
> at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
> 
> at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
> 
> at java.lang.reflect.WeakCache.get(WeakCache.java:127)
> 
> at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
> 
> at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
> 
> at org.neo4j.kernel.impl.util.DependenciesProxy.dependencies(DependenciesProxy.java:55)
> 
> at org.neo4j.kernel.extension.AbstractKernelExtensions.getKernelExtensionDependencies(AbstractKernelExtensions.java:111)
> 
> at org.neo4j.kernel.extension.AbstractKernelExtensions.init(AbstractKernelExtensions.java:59)
> 
> at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:413)
> 
> ... 12 more
> 
> Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.impl.logging.LogService
> 
> at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 
> at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> 
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 
> ... 28 more
> 
> 2018-11-28 20:26:45.172+0000 INFO Neo4j Server shutdown initiated by request

**Comment by MaryamMahmoodi** [comment] 2019-01-20 21:01
I did purge neo4j , and installed neo4j 3.4.10 but after reinstallation neo4j didn't work automatically so I have to use “neo4j console” command anytime
